export { isArray } from './lib/is-array';
export { isBigInt } from './lib/is-big-int';
export { isBoolean } from './lib/is-boolean';
export { isDate } from './lib/is-date';
export { isError } from './lib/is-error';
export { isFunction } from './lib/is-function';
export { isNull } from './lib/is-null';
export { isNumber } from './lib/is-number';
export { isObject } from './lib/is-object';
export { isRegExp } from './lib/is-reg-exp';
export { isString } from './lib/is-string';
export { isSymbol } from './lib/is-symbol';
export { isType } from './lib/is-type';
export { isUndefined } from './lib/is-undefined';
export { notNil } from './lib/not-nil';
export type { AnyFunction } from './lib/any-function.d';
export type { IsTypeKeyType } from './lib/is-type-key-type.d';
export type { IsTypeKey } from './lib/is-type-key.d';
export type { UnknownFunction } from './lib/unknown-function.d';
